### ISSUE TITLE
LostArk Hotfix - Damage Meter doesn't work anymore (Updated Version)

### ISSUE THREAD

**Issue by mugennoyami** [rivellathetank/la-metrum#3]
Basically the tile says it all.

Kind unlucky since you made a push just 1 day prior x)

Would be cool if you could update it! 

Have a nice day!
Cheers!

**Comment by rivellathetank** [comment]
Thanks for letting me know. I don't check for client updates outside of reset days, so I really appreciate your notifying me about the hotfix.

I've released an update here: https://github.com/rivellathetank/la-metrum/releases/tag/v1.3.0.
