### ISSUE TITLE
Version not up to date anymore

### ISSUE THREAD

**Issue by mugennoyami** [rivellathetank/la-metrum#4]
Cheers. Just wanted to let you know that the version doesn't work anymore. I don't know if you still want to update it or if you're going to stop working on it.

Might it be possible to add an auto update function or just make it so, that it doesn't depend on the version?

Not sure how LOA Details has worked around that issue, but it seems there never is an update requiered.

Cheers & have a nice day!

**Comment by rivellathetank** [comment]
Thanks for letting me know. I've released an update: https://github.com/rivellathetank/la-metrum/releases/tag/v1.6.0.

> Might it be possible to add an auto update function or just make it so, that it doesn't depend on the version?

I'm afraid it's not possible. LaMetrum breaks when the binary protocol used by the Lost Ark client-server communication changes. When this happens, I need to make manual changes in LaMetrum that cannot be automated. Sometimes (although this isn't frequent), the only thing I need to change is the compatibility version. Here's an example of such a commit: https://github.com/rivellathetank/la-metrum/commit/af081066138f6b696e89b161b9c6d3de5d5409e0. Other times I need to change quite a bit of code: https://github.com/rivellathetank/la-metrum/commit/c2ef3fc1f40e58b00e3805f9e11a62e7f11adba0.

Are you on Gang discord? I'm going to start a discussion there about migration away from LaMetrum. If you aren't on Gang discord, I can post a copy here for your benefit.

**Comment by mugennoyami** [comment]
Ah i see. Interesting! 

No I´m not on there unfortunately. 

Feel free to send me an invite! <3

**Comment by rivellathetank** [comment]
I'll repost it here.

---

When I quit LA, LaMetrum was the only working Damage Meter for Lost Ark and I promised to keep maintaining it until a reasonable alternative appears on the scene. Back then the most promising candidate was https://github.com/lost-ark-dev/loa-details and it's possible that it has matured enough to be usable. Have any of you tried it? Does it work? Or perhaps there is another Damage Meter you know about that works?

Feel free to reply to me personally on Discord if you are wary of admitting in public of using a Damage Meter (an attitude I would recommend: can never be too cautious). You can also use my email (see https://github.com/rivellathetank) or open an issue on https://github.com/rivellathetank/la-metrum. Any experience you can share about alternative Lost Ark Damage Meters would be welcome.

P.S.

If I promised you some feature or improvement for LaMetrum, I'm afraid I'll have to default on it. Keeping LaMetrum running in its current state is the extent of my commitment at this point.
